name: AlmostHardcore
main: org.c0z3n.AlmostHardcore
author: c0z3n
website: https://github.com/c0z3n
version: 0.1
database: true
commands:
    mydeaths:
        description: see your number of deaths and the server total
        usage: /<command>
    deaths:
        description: print the server death scoreboard
        usage: /<command>